version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres-carsDB
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_DB}
    ports:
      - 5432:5432


      

