version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSORD: ${DB_PW}
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5432:5432


      

